[package]
name = "picomp3lib-rs"
version = "0.1.0"
edition = "2021"

[features]
# add some performance-critical functions to .data memory section
code-in-ram = []
# exclude from compilation functions that exist for dealing with mp3 info in static memory
# picomp3lib uses static memory for any target that doesn't have alloc, because the library uses opaque pointers
# we provide concrete structs for all info, so the user can store in static/stack/Box
byo-buffers = []

[build-dependencies]
cc = "1.0"

[dependencies]
libc = "0.2"

[dev-dependencies]
byte-slice-cast = { version = "1.2.2" }
