[package]
name = "picomp3lib-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1.0"

[dependencies]
libc = "0.2"
byte-slice-cast = { version = "1.2.2", optional = true }

[[bin]]
# convert mp3 to raw, using the FFI interface directly
name = "ffimp3toraw"
path = "src/ffi_mp3_to_raw.rs"
required-features = ["byte-slice-cast"]

# convert mp3 to raw, using the wrapper interface
[[bin]]
name = "mp3toraw"
path = "src/mp3_to_raw.rs"
required-features = ["byte-slice-cast"]

[[bin]]
name = "mp3toraw_fixed"
path = "src/mp3_to_raw_fixed.rs"
required-features = ["byte-slice-cast"]

# try to decode an mp3 loaded in smaller chunks instead of one big buffer
[[bin]]
name = "loadchunks"
path = "src/load_chunks.rs"
required-features = ["byte-slice-cast"]

# cargo build/run
[profile.dev]
codegen-units = 1
# can't run debug when enabling ram functions. 
debug = 0
debug-assertions = true
incremental = false
opt-level = 3
overflow-checks = true

# cargo build/run --release
[profile.release]
codegen-units = 1
debug = 0
debug-assertions = false
incremental = false
# lto = 'fat' causes the mp3 lib to break. need to diagnose that
lto = "off"
opt-level = 3
overflow-checks = false