[package]
name = "picomp3lib-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1.0"

[dependencies]
libc = "0.2"


# cargo build/run
[profile.dev]
codegen-units = 1
# can't run debug when enabling ram functions. 
debug = 0
debug-assertions = true
incremental = false
opt-level = 3
overflow-checks = true

# cargo build/run --release
[profile.release]
codegen-units = 1
debug = 0
debug-assertions = false
incremental = false
# lto = 'fat' causes the mp3 lib to break. need to diagnose that
lto = "off"
opt-level = 3
overflow-checks = false