[package]
name = "picomp3lib-rs"
version = "0.1.0"
edition = "2021"

[features]
# add some performance-critical functions to .data memory section
code-in-ram = []

[build-dependencies]
cc = "1.0"

[dependencies]
libc = "0.2"
hound = {version = "3.5", optional = true }

[dev-dependencies]
byte-slice-cast = { version = "1.2.2" }

[[example]]
name = "ffi_mp3_to_raw"

[[example]]
name = "mp3_to_wave"
required-features = ["hound"]

[[example]]
name = "load_chunks_wave"
required-features = ["hound"]

[[example]]
name = "easymode_wave"
required-features = ["hound"]