[package]
name = "picomp3lib-rs"
version = "0.1.0"
edition = "2021"

[features]
# add some performance-critical functions to .data memory section
code-in-ram = []
# picomp3lib (the C lib) uses static memory for any target that doesn't have alloc and hides this behind an opaque pointer.
# The default impl for picomp3lib-rs uses concrete structs for all info, so the user can choose to store in static/stack/Box.
# If you enable this feature, you opt out of this and will get an opaque pointer and statically allocated structures
# Notes: this is slower that the default setting. on cortex-m, this also breaks if you enable LTO. enable at your own risk!
use-static-buffers = []

[build-dependencies]
cc = "1.0"

[dependencies]
libc = "0.2"
hound = {version = "3.5", optional = true }

[dev-dependencies]
byte-slice-cast = { version = "1.2.2" }

[[example]]
name = "ffi_mp3_to_raw"
required-features = ["use-static-buffers"]

[[example]]
name = "mp3_to_wave"
required-features = ["hound"]