//! no_std Rust wrapper for the libhelix fixed-point mp3 decoder
//!
//! Rust ports of high-level C library functions live in [mp3::Mp3]
//!
//! The underlying C mp3 library is exposed through [ffi]
#![no_std]

// Allow the code generated by bindgen to break style rules
#[allow(dead_code)]
#[allow(non_camel_case_types)]
#[allow(non_upper_case_globals)]
#[allow(non_snake_case)]
pub mod ffi;

// pub use mp3::Mp3;
pub mod mp3;
