//! Rust bindings and high-level wrapper for `ThreePM` - which is a fixed-point MP3 decoder library written in C
#![no_std]

// Allow the code generated by bindgen to break style rules
#[allow(dead_code)]
#[allow(non_camel_case_types)]
#[allow(non_upper_case_globals)]
#[allow(non_snake_case)]
/// Autogenerated (via bindgen) interfaces to the C ThreePM library
pub mod ffi;

mod contig_buffer;
pub mod easy_mode;
pub mod mp3;
